// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXJBoeifIcW3PmH2RDkBty-6YbNcxtTZI',
    appId: '1:836347347495:web:a9ac3120a2a7408e584402',
    messagingSenderId: '836347347495',
    projectId: 'buzz-hive-b96b9',
    authDomain: 'buzz-hive-b96b9.firebaseapp.com',
    storageBucket: 'buzz-hive-b96b9.appspot.com',
    measurementId: 'G-TF30S8D1ZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_1BAcGCrcKC7ZzMJCXDnJ4tCtN9FlFc4',
    appId: '1:836347347495:android:6b615ff06a662099584402',
    messagingSenderId: '836347347495',
    projectId: 'buzz-hive-b96b9',
    storageBucket: 'buzz-hive-b96b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1b4xfsnJlATnOm_1oCX02RQvJSjuxAO4',
    appId: '1:836347347495:ios:f8177bcdd110f674584402',
    messagingSenderId: '836347347495',
    projectId: 'buzz-hive-b96b9',
    storageBucket: 'buzz-hive-b96b9.appspot.com',
    iosBundleId: 'com.example.buzzHive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1b4xfsnJlATnOm_1oCX02RQvJSjuxAO4',
    appId: '1:836347347495:ios:f8177bcdd110f674584402',
    messagingSenderId: '836347347495',
    projectId: 'buzz-hive-b96b9',
    storageBucket: 'buzz-hive-b96b9.appspot.com',
    iosBundleId: 'com.example.buzzHive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXJBoeifIcW3PmH2RDkBty-6YbNcxtTZI',
    appId: '1:836347347495:web:a0f560299b4ffd90584402',
    messagingSenderId: '836347347495',
    projectId: 'buzz-hive-b96b9',
    authDomain: 'buzz-hive-b96b9.firebaseapp.com',
    storageBucket: 'buzz-hive-b96b9.appspot.com',
    measurementId: 'G-98XPMTMKD2',
  );
}
